version: '3.3'
services:
  devopsproject:
    image: roykoren10/devopsproject:main
    container_name: DevopsProject
    hostname: DevopsProject
    environment:
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8000:8000"
  devopsprojectfe:
    image: roykoren10/devopsprojectfe:main
    container_name: DevopsProjectFE
    hostname: DevopsProjectFE
    ports:
      - "80:80"
  mongo:
    image: mongo:5.0
    container_name: DevopsMongo
    hostname: DevopsMongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb: