name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: export tagname=$(date +%s)
    - run: docker build . --file Dockerfile --tag devopsproject:$tagname
    - run: docker push roykoren10/devopsproject:$tagname
    - run: docker build ./FE --file Dockerfile --tag devopsprojectfe:$tagname
    - run: docker push roykoren10/devopsproject:$tagname
