name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
        Tagname: date +%s
    steps:
    - uses: actions/checkout@v3
    - run: echo "$Tagname" 
    - name: Build the BE image
      run: docker build . --file Dockerfile --tag devopsproject:$Tagname
    - run: docker push roykoren10/devopsproject:$Tagname
    - name: Build the FE image
      run: docker build ./FE --file Dockerfile --tag devopsprojectfe:$Tagname
    - run: docker push roykoren10/devopsproject:$tagname
